### ISSUE TITLE
qr.md is missing property descriptions

### ISSUE THREAD

**Issue by nmummau** [pdfmake/docs#9]
Without knowing how the guts of the pdfmake source code creates QR codes, I cannot fix this myself without digging through code and figuring it out.

[qr.md](https://github.com/pdfmake/docs/blob/8a7fb7c9cc2f1b96c685ef81643a3017eab5422c/content/document-definition-object/qr.md) lists all of the properties available for a QR code but does not describe them with data type, descriptions, optional values, or default values.

Would be nice to add this information to these properties.

**Comment by liborm85** [comment]
updated, see [qr.md](https://github.com/pdfmake/docs/blob/master/content/document-definition-object/qr.md)
